import {OPERATION_TYPE_EXTRACTION} from "../../../enums/operationsTypes/extractions/operationType_extractions.enum";

export type Extraction =
    OPERATION_TYPE_EXTRACTION.KEY_VALUE_EXTRACTION |
    OPERATION_TYPE_EXTRACTION.TEXT_EXTRACTION |
    OPERATION_TYPE_EXTRACTION.TABLE_EXTRACTION |
    OPERATION_TYPE_EXTRACTION.COLUMN_EXTRACTION |
    OPERATION_TYPE_EXTRACTION.ROW_EXTRACTION |
    OPERATION_TYPE_EXTRACTION.CELL_EXTRACTION |
    OPERATION_TYPE_EXTRACTION.IMAGE_EXTRACTION |
    OPERATION_TYPE_EXTRACTION.AUDIO_EXTRACTION;
