import {REALTIME_DATABASE_PATHS} from "./realtimeDatabasePaths";
import {MIME_TYPE} from "../enums/mimeType.enum"
import {RealtimeDatabasePaths} from "../models/RealtimeDatabasePaths";

export const mimeTypeToDatabasePathMapper: { [K in MIME_TYPE]: RealtimeDatabasePaths[keyof RealtimeDatabasePaths] } = {
    [MIME_TYPE.PNG]: REALTIME_DATABASE_PATHS.IMAGES,
    [MIME_TYPE.JPG]: REALTIME_DATABASE_PATHS.IMAGES,
    [MIME_TYPE.JPEG]: REALTIME_DATABASE_PATHS.IMAGES,
    [MIME_TYPE.GIF]: REALTIME_DATABASE_PATHS.IMAGES,
    [MIME_TYPE.CSV]: REALTIME_DATABASE_PATHS.CSV,
    [MIME_TYPE.JSON]: REALTIME_DATABASE_PATHS.JSON,
    [MIME_TYPE.XML]: REALTIME_DATABASE_PATHS.XML,
    [MIME_TYPE.PDF]: REALTIME_DATABASE_PATHS.PDF,
    [MIME_TYPE.PLAIN]: REALTIME_DATABASE_PATHS.TXT,
    [MIME_TYPE.MSWORD]: REALTIME_DATABASE_PATHS.DOC,
    [MIME_TYPE.DOCX]: REALTIME_DATABASE_PATHS.DOCX,
    [MIME_TYPE.EXCEL]: REALTIME_DATABASE_PATHS.XLS,
    [MIME_TYPE.XLSX]: REALTIME_DATABASE_PATHS.XLSX,
    [MIME_TYPE.PPT]: REALTIME_DATABASE_PATHS.PPT,
    [MIME_TYPE.PPTX]: REALTIME_DATABASE_PATHS.PPTX
};
