import {OPERATION_TYPE} from "../../enums/operationsTypes/operationType.enum";

export type OperationType =
    OPERATION_TYPE.CALCULATION |
    OPERATION_TYPE.CLASSIFICATION |
    OPERATION_TYPE.COMPARISON |
    OPERATION_TYPE.EXPORT |
    OPERATION_TYPE.EXTRACTION |
    OPERATION_TYPE.GENERATION |
    OPERATION_TYPE.IMPORT |
    OPERATION_TYPE.SENTIMENT |
    OPERATION_TYPE.SUMMARIZATION |
    OPERATION_TYPE.TRANSFORMATION |
    OPERATION_TYPE.TRANSLATION |
    null;
