import {APP_MODE} from "../enums/appMode.enum";

export type AppMode =
    APP_MODE.DEFAULT |
    APP_MODE.PIPELINE_DELETION |
    APP_MODE.TEMPLATE_DELETION |
    APP_MODE.TEMPLATE_CREATION_BY_PIPELINE_BUILDER |
    APP_MODE.TEMPLATE_ADDITION_TO_PIPELINE |
    APP_MODE.OPERATION_CREATION_FROM_TEMPLATE |
    APP_MODE.OPERATIONS_DELETION;
