import {SOURCE_TYPE_PICKER_TYPES} from "../enums/sourceTypePickerTypes.enum";

export type SourceTypePickerSetting = SOURCE_TYPE_PICKER_TYPES.FILE |
    SOURCE_TYPE_PICKER_TYPES.DATABASE |
    SOURCE_TYPE_PICKER_TYPES.API |
    SOURCE_TYPE_PICKER_TYPES.WEB |
    SOURCE_TYPE_PICKER_TYPES.STREAM;
