export type Transformation =
    'transform-to-csv' |
    'transform-to-json' |
    'transform-to-xml' |
    'transform-to-yaml' |
    'transform-to-sql' |
    'transform-to-html' |
    'transform-to-markdown' |
    'transform-to-pdf' |
    'transform-to-docx' |
    'transform-to-xlsx' |
    'transform-to-pptx' |
    'transform-to-odt' |
    'transform-to-ods' |
    'transform-to-odp' |
    'transform-to-rtf' |
    'transform-to-txt' |
    'transform-to-epub' |
    'transform-to-mobi' |
    'transform-to-mp3' |
    'transform-to-wav' |
    'transform-to-ogg' |
    'transform-to-flac' |
    'transform-to-png' |
    'transform-to-jpg' |
    'transform-to-gif' |
    'transform-to-bmp' |
    'transform-to-tiff' |
    'transform-to-svg' |
    'transform-to-mpg' |
    'transform-to-mp2' |
    'transform-to-mpeg' |
    'transform-to-mpe' |
    'transform-to-mpv' |
    'transform-to-mp4' |
    'transform-to-m4p' |
    'transform-to-m4v' |
    'transform-to-webm' |
    'transform-to-wmv' |
    'transform-to-mov' |
    'transform-to-qt' |
    'transform-to-avi' |
    'transform-to-flv';
